[features]
seeds = false
skip-lint = false
[programs.devnet]
switchboard_feed_solana = "GWLjdS5qvUUwTt8HHVTHmJ8F4ZmNYRvdNoiL8gBgc5H7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anonymous/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
